// Code generated by mocktail; DO NOT EDIT.

package logger

import (
	"github.com/stretchr/testify/mock"
	"go.uber.org/zap"
	"testing"
)

// iZapLoggerMock mock of IUserConsumer.
type iZapLoggerMock struct{ mock.Mock }

// NewIZapLoggerMock creates a new iZapLoggerMock.
func NewIZapLoggerMock(tb testing.TB) *iZapLoggerMock {
	tb.Helper()

	m := &iZapLoggerMock{}
	m.Mock.Test(tb)

	tb.Cleanup(func() { m.AssertExpectations(tb) })

	return m
}


func (m *iZapLoggerMock) Info(fnName string, fields ...zap.Field) {
	m.Called(fnName) // ignore fields for compatibility
}

func (m *iZapLoggerMock) Error(fnName string, fields ...zap.Field) {
	m.Called(fnName) // ignore fields for compatibility
}

func (m *iZapLoggerMock) Debug(fnName string, fields ...zap.Field) {
	m.Called(fnName) // ignore fields for compatibility
}
