spring:
  application:
    name: commerce-service

  config:
    import: "consul:"

  data:
    mongodb:
      uri: mongodb://mongo:1234@localhost:27017/commerce?directConnection=true&replicaSet=rs0
      database: commerce

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: commerce-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  cloud:
    consul:

      host: localhost
      port: 8500

      config:
        prefix: config
        default-context: application
        profile-separator: ","

      discovery:
        enabled: true
        instance-id: commerce-service
        serviceName: ${spring.application.name}
        management-port: ${server.grpc.port}
        management-tags:
          - service
          - kafka-subscriber
        healthCheckPath: ${management.server.servlet.context-path}/check
        healthCheckInterval: 15s

server:
  port: 40051

  grpc:
    port: 50051

  metric:
    port: 30051

logging:
  level:
    root: INFO
    com.ferza17.ecommercemicroservicesv2: DEBUG
    io.grpc: DEBUG