version: "3.8"
name: "E-COMMERCE_V2"
services:

  postgres-local:
    container_name: postgres-local
    ports:
      - '5432:5432'
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./entrypoint/postgres:/docker-entrypoint-initdb.d
    networks:
      - local

  mongo-local:
    container_name: mongo-local
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - local

# FOR TEST EMAIL NOTIFICATION
  mailhog-local:
    image: mailhog/mailhog:latest
    container_name: mailhog-local
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - local

  redis-local:
    container_name: redis-local
    ports:
      - '6379:6379'
    image: redis:latest
    networks:
      - local

  rabbitmq-local:
    container_name: rabbitmq-local
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "1234"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    volumes:
      - ./entrypoint/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - local

# FOR TRACING
  jaeger-local:
    container_name: jaeger-local
    image: jaegertracing/all-in-one:1.37
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'

  elasticsearch-local:
    container_name: elasticsearch-local
    image: elasticsearch:8.4.1
    restart: always
    environment:
      - "discovery.type=single-node"
      - "cluster.name=products"
      - "node.name=node1"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - local

  kibana-local:
    container_name: kibana-local
    image: kibana:8.4.1
    depends_on:
      - elasticsearch-local
    ports:
      - '5601:5601'
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch-local:9200'
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - local

networks:
  local:
    driver: bridge