// This file is @generated by prost-build.
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PaymentStatus {
    Pending = 0,
    Partial = 1,
    Success = 2,
    Failed = 3,
}
impl PaymentStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "PENDING",
            Self::Partial => "PARTIAL",
            Self::Success => "SUCCESS",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PENDING" => Some(Self::Pending),
            "PARTIAL" => Some(Self::Partial),
            "SUCCESS" => Some(Self::Success),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProviderMethod {
    Bank = 0,
    CryptoCurrency = 1,
    Debit = 2,
    Credit = 3,
    CashOnDelivery = 4,
}
impl ProviderMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Bank => "BANK",
            Self::CryptoCurrency => "CRYPTO_CURRENCY",
            Self::Debit => "DEBIT",
            Self::Credit => "CREDIT",
            Self::CashOnDelivery => "CASH_ON_DELIVERY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BANK" => Some(Self::Bank),
            "CRYPTO_CURRENCY" => Some(Self::CryptoCurrency),
            "DEBIT" => Some(Self::Debit),
            "CREDIT" => Some(Self::Credit),
            "CASH_ON_DELIVERY" => Some(Self::CashOnDelivery),
            _ => None,
        }
    }
}
/// REFERRED TO DATABASE SCHEMA
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaymentItem {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.PaymentItem.id")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[validate(name = "payment.PaymentItem.productId")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    #[validate(name = "payment.PaymentItem.amount")]
    pub amount: f64,
    #[prost(int32, tag = "4")]
    #[validate(name = "payment.PaymentItem.qty")]
    pub qty: i32,
    #[prost(string, tag = "5")]
    #[validate(name = "payment.PaymentItem.payment_id")]
    pub payment_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    #[validate(name = "payment.PaymentItem.created_at")]
    #[schema(value_type = String, format = "date-time")]
    pub created_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    #[validate(name = "payment.PaymentItem.updated_at")]
    #[schema(value_type = String, format = "date-time")]
    pub updated_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    #[validate(name = "payment.PaymentItem.discarded_at")]
    #[schema(value_type = String, format = "date-time")]
    pub discarded_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
}
/// REFERRED TO DATABASE SCHEMA
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Provider {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.Provider.id")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[validate(name = "payment.Provider.name")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "ProviderMethod", tag = "3")]
    #[validate(name = "payment.Provider.method")]
    pub method: i32,
    #[prost(message, optional, tag = "8")]
    #[validate(name = "payment.Provider.created_at")]
    #[schema(value_type = String, format = "date-time")]
    pub created_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    #[validate(name = "payment.Provider.updated_at")]
    #[schema(value_type = String, format = "date-time")]
    pub updated_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    #[validate(name = "payment.Provider.discarded_at")]
    #[schema(value_type = String, format = "date-time")]
    pub discarded_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
}
/// REFERRED TO DATABASE SCHEMA
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Payment {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.Payment.id")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[validate(name = "payment.Payment.code")]
    pub code: ::prost::alloc::string::String,
    #[prost(double, tag = "4")]
    #[validate(name = "payment.Payment.total_price")]
    pub total_price: f64,
    #[prost(enumeration = "PaymentStatus", tag = "5")]
    #[validate(name = "payment.Payment.status")]
    pub status: i32,
    #[prost(string, tag = "6")]
    #[validate(name = "payment.Payment.provider_id")]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    #[validate(name = "payment.Payment.user_id")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    #[validate(name = "payment.Payment.created_at")]
    #[schema(value_type = String, format = "date-time")]
    pub created_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    #[validate(name = "payment.Payment.updated_at")]
    #[schema(value_type = String, format = "date-time")]
    pub updated_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    #[validate(name = "payment.Payment.discarded_at")]
    #[schema(value_type = String, format = "date-time")]
    pub discarded_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
}
/// PAYMENT REQUEST DEFINITION
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePaymentRequest {
    #[prost(message, repeated, tag = "1")]
    #[validate(name = "payment.CreatePaymentRequest.items")]
    #[validate(r#type(repeated(ignore_empty = true)))]
    pub items: ::prost::alloc::vec::Vec<PaymentItem>,
    #[prost(string, tag = "2")]
    #[validate(name = "payment.CreatePaymentRequest.user_id")]
    #[validate(r#type(string(ignore_empty = false)))]
    pub user_id: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    #[validate(name = "payment.CreatePaymentRequest.amount")]
    #[validate(r#type(double(gt = 0.0)))]
    pub amount: f64,
    #[prost(string, tag = "4")]
    #[validate(name = "payment.CreatePaymentRequest.provider_id")]
    #[validate(r#type(string(ignore_empty = false)))]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    #[validate(name = "payment.CreatePaymentRequest.shipping_provider_id")]
    #[validate(r#type(string(ignore_empty = false)))]
    pub shipping_provider_id: ::prost::alloc::string::String,
}
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaymentOrderDelayedCancelledRequest {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.PaymentOrderDelayedCancelledRequest.id")]
    #[validate(r#type(string(ignore_empty = false)))]
    pub id: ::prost::alloc::string::String,
}
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallBackPaymentRequest {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.CallBackPaymentRequest.payment_id")]
    #[validate(r#type(string(min_len = 1)))]
    pub payment_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    #[validate(name = "payment.CallBackPaymentRequest.amount")]
    #[validate(r#type(double(gt = 0.0)))]
    pub amount: f64,
}
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindPaymentByIdRequest {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.FindPaymentByIdRequest.id")]
    #[validate(r#type(string(min_len = 1)))]
    pub id: ::prost::alloc::string::String,
}
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindPaymentByUserIdAndStatusRequest {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.FindPaymentByUserIdAndStatusRequest.user_id")]
    #[validate(r#type(string(min_len = 1)))]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "PaymentStatus", tag = "2")]
    #[validate(name = "payment.FindPaymentByUserIdAndStatusRequest.status")]
    #[validate(r#type(r#enum(defined_only = true)))]
    pub status: i32,
}
/// PAYMENT PROVIDER REQUEST DEFINITION
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindPaymentProvidersRequest {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.FindPaymentProvidersRequest.name")]
    #[validate(r#type(string(min_len = 1)))]
    pub name: ::prost::alloc::string::String,
}
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindPaymentProviderByIdRequest {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.FindPaymentProviderByIdRequest.id")]
    #[validate(r#type(string(min_len = 1)))]
    pub id: ::prost::alloc::string::String,
}
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePaymentResponse {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.CreatePaymentResponse.message")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[validate(name = "payment.CreatePaymentResponse.status")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    #[validate(name = "payment.CreatePaymentResponse.data")]
    pub data: ::core::option::Option<create_payment_response::CreatePaymentResponseData>,
}
/// Nested message and enum types in `CreatePaymentResponse`.
pub mod create_payment_response {
    #[derive(::prost_validate::Validator)]
    #[derive(utoipa::ToSchema)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct CreatePaymentResponseData {
        #[prost(string, tag = "1")]
        #[validate(name = "payment.CreatePaymentResponse.CreatePaymentResponseData.id")]
        pub id: ::prost::alloc::string::String,
    }
}
/// PAYMENT PROVIDER PROTO DEFINITION
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindPaymentProviderByIdResponse {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.FindPaymentProviderByIdResponse.message")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[validate(name = "payment.FindPaymentProviderByIdResponse.status")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    #[validate(name = "payment.FindPaymentProviderByIdResponse.data")]
    pub data: ::core::option::Option<Provider>,
}
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindPaymentProvidersResponse {
    #[prost(string, tag = "1")]
    #[validate(name = "payment.FindPaymentProvidersResponse.message")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[validate(name = "payment.FindPaymentProvidersResponse.status")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    #[validate(name = "payment.FindPaymentProvidersResponse.data")]
    pub data: ::core::option::Option<
        find_payment_providers_response::FindPaymentProvidersResponseData,
    >,
}
/// Nested message and enum types in `FindPaymentProvidersResponse`.
pub mod find_payment_providers_response {
    #[derive(::prost_validate::Validator)]
    #[derive(utoipa::ToSchema)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct FindPaymentProvidersResponseData {
        #[prost(message, repeated, tag = "1")]
        #[validate(
            name = "payment.FindPaymentProvidersResponse.FindPaymentProvidersResponseData.providers"
        )]
        pub providers: ::prost::alloc::vec::Vec<super::Provider>,
        #[prost(uint32, tag = "2")]
        #[validate(
            name = "payment.FindPaymentProvidersResponse.FindPaymentProvidersResponseData.page"
        )]
        pub page: u32,
        #[prost(uint32, tag = "3")]
        #[validate(
            name = "payment.FindPaymentProvidersResponse.FindPaymentProvidersResponseData.limit"
        )]
        pub limit: u32,
    }
}
/// Generated client implementations.
pub mod payment_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PaymentServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PaymentServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PaymentServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PaymentServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PaymentServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// COMMAND
        pub async fn create_payment(
            &mut self,
            request: impl tonic::IntoRequest<super::CreatePaymentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreatePaymentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payment.PaymentService/CreatePayment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("payment.PaymentService", "CreatePayment"));
            self.inner.unary(req, path, codec).await
        }
        /// QUERY
        pub async fn find_payment_by_id(
            &mut self,
            request: impl tonic::IntoRequest<super::FindPaymentByIdRequest>,
        ) -> std::result::Result<tonic::Response<super::Payment>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payment.PaymentService/FindPaymentById",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("payment.PaymentService", "FindPaymentById"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn find_payment_by_user_id_and_status(
            &mut self,
            request: impl tonic::IntoRequest<super::FindPaymentByUserIdAndStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::Payment>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payment.PaymentService/FindPaymentByUserIdAndStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payment.PaymentService",
                        "FindPaymentByUserIdAndStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod payment_provider_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PaymentProviderServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PaymentProviderServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PaymentProviderServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PaymentProviderServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PaymentProviderServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// QUERY
        pub async fn find_payment_providers(
            &mut self,
            request: impl tonic::IntoRequest<super::FindPaymentProvidersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindPaymentProvidersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payment.PaymentProviderService/FindPaymentProviders",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payment.PaymentProviderService",
                        "FindPaymentProviders",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn find_payment_provider_by_id(
            &mut self,
            request: impl tonic::IntoRequest<super::FindPaymentProviderByIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindPaymentProviderByIdResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payment.PaymentProviderService/FindPaymentProviderById",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payment.PaymentProviderService",
                        "FindPaymentProviderById",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod payment_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PaymentServiceServer.
    #[async_trait]
    pub trait PaymentService: std::marker::Send + std::marker::Sync + 'static {
        /// COMMAND
        async fn create_payment(
            &self,
            request: tonic::Request<super::CreatePaymentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreatePaymentResponse>,
            tonic::Status,
        >;
        /// QUERY
        async fn find_payment_by_id(
            &self,
            request: tonic::Request<super::FindPaymentByIdRequest>,
        ) -> std::result::Result<tonic::Response<super::Payment>, tonic::Status>;
        async fn find_payment_by_user_id_and_status(
            &self,
            request: tonic::Request<super::FindPaymentByUserIdAndStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::Payment>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct PaymentServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PaymentServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PaymentServiceServer<T>
    where
        T: PaymentService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/payment.PaymentService/CreatePayment" => {
                    #[allow(non_camel_case_types)]
                    struct CreatePaymentSvc<T: PaymentService>(pub Arc<T>);
                    impl<
                        T: PaymentService,
                    > tonic::server::UnaryService<super::CreatePaymentRequest>
                    for CreatePaymentSvc<T> {
                        type Response = super::CreatePaymentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreatePaymentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PaymentService>::create_payment(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreatePaymentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payment.PaymentService/FindPaymentById" => {
                    #[allow(non_camel_case_types)]
                    struct FindPaymentByIdSvc<T: PaymentService>(pub Arc<T>);
                    impl<
                        T: PaymentService,
                    > tonic::server::UnaryService<super::FindPaymentByIdRequest>
                    for FindPaymentByIdSvc<T> {
                        type Response = super::Payment;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FindPaymentByIdRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PaymentService>::find_payment_by_id(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FindPaymentByIdSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payment.PaymentService/FindPaymentByUserIdAndStatus" => {
                    #[allow(non_camel_case_types)]
                    struct FindPaymentByUserIdAndStatusSvc<T: PaymentService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: PaymentService,
                    > tonic::server::UnaryService<
                        super::FindPaymentByUserIdAndStatusRequest,
                    > for FindPaymentByUserIdAndStatusSvc<T> {
                        type Response = super::Payment;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::FindPaymentByUserIdAndStatusRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PaymentService>::find_payment_by_user_id_and_status(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FindPaymentByUserIdAndStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PaymentServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "payment.PaymentService";
    impl<T> tonic::server::NamedService for PaymentServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated server implementations.
pub mod payment_provider_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PaymentProviderServiceServer.
    #[async_trait]
    pub trait PaymentProviderService: std::marker::Send + std::marker::Sync + 'static {
        /// QUERY
        async fn find_payment_providers(
            &self,
            request: tonic::Request<super::FindPaymentProvidersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindPaymentProvidersResponse>,
            tonic::Status,
        >;
        async fn find_payment_provider_by_id(
            &self,
            request: tonic::Request<super::FindPaymentProviderByIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindPaymentProviderByIdResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct PaymentProviderServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PaymentProviderServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for PaymentProviderServiceServer<T>
    where
        T: PaymentProviderService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/payment.PaymentProviderService/FindPaymentProviders" => {
                    #[allow(non_camel_case_types)]
                    struct FindPaymentProvidersSvc<T: PaymentProviderService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: PaymentProviderService,
                    > tonic::server::UnaryService<super::FindPaymentProvidersRequest>
                    for FindPaymentProvidersSvc<T> {
                        type Response = super::FindPaymentProvidersResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FindPaymentProvidersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PaymentProviderService>::find_payment_providers(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FindPaymentProvidersSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payment.PaymentProviderService/FindPaymentProviderById" => {
                    #[allow(non_camel_case_types)]
                    struct FindPaymentProviderByIdSvc<T: PaymentProviderService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: PaymentProviderService,
                    > tonic::server::UnaryService<super::FindPaymentProviderByIdRequest>
                    for FindPaymentProviderByIdSvc<T> {
                        type Response = super::FindPaymentProviderByIdResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::FindPaymentProviderByIdRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PaymentProviderService>::find_payment_provider_by_id(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FindPaymentProviderByIdSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PaymentProviderServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "payment.PaymentProviderService";
    impl<T> tonic::server::NamedService for PaymentProviderServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
