// This file is @generated by prost-build.
#[derive(::prost_validate::Validator)]
#[derive(utoipa::ToSchema)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(string, tag = "1")]
    #[validate(name = "response.Response.error")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[validate(name = "response.Response.message")]
    pub message: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    #[validate(name = "response.Response.Code")]
    pub code: i32,
    #[prost(message, optional, tag = "4")]
    #[validate(name = "response.Response.data")]
    #[schema(value_type = serde_json::Value)]
    pub data: ::core::option::Option<::prost_wkt_types::Struct>,
}
