http:
  routers:
    user-service-auth-grpc:
      entryPoints:
        - grpc
      service: "user-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/user.AuthService`)"
      tls: false

    user-service-user-grpc:
      entryPoints:
        - grpc
      service: "user-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/user.UserService`)"
      tls: false

    user-service-user-http:
      entryPoints:
        - web
      service: "user-service-http"
      rule: "Host(`localhost`) && (PathPrefix(`/v1/user`) || PathPrefix(`/docs/v1/user`))"
      tls: false

    product-service-grpc:
      entryPoints:
        - grpc
      service: "product-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/product.ProductService`)"
      tls: false

    product-service-product-http:
      entryPoints:
        - web
      service: "product-service-http"
      rule: "Host(`localhost`) && (PathPrefix(`/v1/product`) || PathPrefix(`/docs/v1/product`))"
      tls: false

    payment-service-provider-grpc:
      entryPoints:
        - grpc
      service: "payment-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/payment.ProviderService`)"
      tls: false

    payment-service-payment-grpc:
      entryPoints:
        - grpc
      service: "payment-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/payment.PaymentService`)"
      tls: false

    payment-service-http:
      entryPoints:
        - web
      service: "payment-service-http"
      rule: "Host(`localhost`) && (PathPrefix(`/v1/payment`) || PathPrefix(`/docs/v1/payment`))"
      tls: false


    grpc-reflection:
      entryPoints:
        - grpc
      service: "user-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/grpc.reflection.v1alpha.ServerReflection`)"
      tls: false

  services:
    user-service-grpc:
      loadBalancer:
        servers:
          - url: h2c://user-service:50056

    user-service-http:
      loadBalancer:
        servers:
          - url: http://user-service:40056

    product-service-grpc:
      loadBalancer:
        servers:
          - url: h2c://product-service:50055

    product-service-http:
      loadBalancer:
        servers:
          - url: http://product-service:40055

    payment-service-grpc:
      loadBalancer:
        servers:
          - url: h2c://payment-service:50054

    payment-service-http:
      loadBalancer:
        servers:
          - url: http://payment-service:40054