http:
  routers:
    product-service-grpc:
      entryPoints:
        - grpc
      service: "product-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/product.ProductService`)"
      tls: false

    product-service-product-http:
      entryPoints:
        - websecure
      service: "product-service-http"
      rule: "Host(`localhost`) && (PathPrefix(`/v1/product`) || PathPrefix(`/docs/v1/product`))"
      tls: true

  services:
    product-service-grpc:
      loadBalancer:
        servers:
          - url: h2c://product-service:50055

    product-service-http:
      loadBalancer:
        servers:
          - url: http://product-service:40055