http:
  routers:
    user-service-auth-grpc:
      entryPoints:
        - grpc
      service: "user-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/user.AuthService`)"
      tls: false

    user-service-user-grpc:
      entryPoints:
        - grpc
      service: "user-service-grpc"
      rule: "Host(`localhost`) && PathPrefix(`/user.UserService`)"
      tls: false

    user-service-user-http:
      entryPoints:
        - websecure
      service: "user-service-http"
      rule: "Host(`localhost`) && (PathPrefix(`/v1/user`) || PathPrefix(`/docs/v1/user`))"
      tls: true

  services:
    user-service-grpc:
      loadBalancer:
        servers:
          - url: h2c://user-service:50056

    user-service-http:
      loadBalancer:
        servers:
          - url: http://user-service:40056