// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repository

import (
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/postgresql"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/telemetry"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/pkg/logger"
)

// Injectors from wire.go:

// ProvidePaymentRepository wires dependencies for IPaymentRepository.
func ProvidePaymentRepository() IPaymentRepository {
	iZapLogger := logger.ProvideLogger()
	iPostgreSQLInfrastructure := postgresql.ProvidePostgreSQLInfrastructure(iZapLogger)
	iTelemetryInfrastructure := telemetry.ProvideTelemetry(iZapLogger)
	iPaymentRepository := NewPaymentRepository(iPostgreSQLInfrastructure, iTelemetryInfrastructure, iZapLogger)
	return iPaymentRepository
}
