
global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-local:9090']

  # Jaeger metrics scraping
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger-local:14269']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'user-service-metrics'
    static_configs:
      - targets: [ 'user-service:30056' ]
    scrape_interval: 30s
    metrics_path: /v1/user/metrics

  - job_name: 'notification-service-metrics'
    static_configs:
      - targets: [ 'notification-service:30053' ]
    scrape_interval: 30s
    metrics_path: /v1/notification/metrics

  - job_name: 'product-service-metrics'
    static_configs:
      - targets: [ 'product-service:30055' ]
    scrape_interval: 30s
    metrics_path: /v1/product/metrics