// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: cartMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Qty           int32                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	CratedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=crated_at,json=cratedAt,proto3" json:"crated_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_cartMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartItem) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CartItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItem) GetCratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CratedAt
	}
	return nil
}

func (x *CartItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Qty           int32                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartItemRequest) Reset() {
	*x = CreateCartItemRequest{}
	mi := &file_cartMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartItemRequest) ProtoMessage() {}

func (x *CreateCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartItemRequest.ProtoReflect.Descriptor instead.
func (*CreateCartItemRequest) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCartItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateCartItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCartItemRequest) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CreateCartItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartItemResponse) Reset() {
	*x = CreateCartItemResponse{}
	mi := &file_cartMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartItemResponse) ProtoMessage() {}

func (x *CreateCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartItemResponse.ProtoReflect.Descriptor instead.
func (*CreateCartItemResponse) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCartItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCartItemByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Qty           int32                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemByIdRequest) Reset() {
	*x = UpdateCartItemByIdRequest{}
	mi := &file_cartMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemByIdRequest) ProtoMessage() {}

func (x *UpdateCartItemByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartItemByIdRequest) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCartItemByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCartItemByIdRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateCartItemByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCartItemByIdRequest) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *UpdateCartItemByIdRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateCartItemByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemByIdResponse) Reset() {
	*x = UpdateCartItemByIdResponse{}
	mi := &file_cartMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemByIdResponse) ProtoMessage() {}

func (x *UpdateCartItemByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateCartItemByIdResponse) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCartItemByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemRequest) Reset() {
	*x = DeleteCartItemRequest{}
	mi := &file_cartMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemRequest) ProtoMessage() {}

func (x *DeleteCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartItemRequest) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCartItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DeleteCartItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemResponse) Reset() {
	*x = DeleteCartItemResponse{}
	mi := &file_cartMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemResponse) ProtoMessage() {}

func (x *DeleteCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteCartItemResponse) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCartItemResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindCartItemsWithPaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProductIds    []string               `protobuf:"bytes,2,rep,name=productIds,proto3" json:"productIds,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCartItemsWithPaginationRequest) Reset() {
	*x = FindCartItemsWithPaginationRequest{}
	mi := &file_cartMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCartItemsWithPaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCartItemsWithPaginationRequest) ProtoMessage() {}

func (x *FindCartItemsWithPaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCartItemsWithPaginationRequest.ProtoReflect.Descriptor instead.
func (*FindCartItemsWithPaginationRequest) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{7}
}

func (x *FindCartItemsWithPaginationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindCartItemsWithPaginationRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *FindCartItemsWithPaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindCartItemsWithPaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FindCartItemsWithPaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCartItemsWithPaginationResponse) Reset() {
	*x = FindCartItemsWithPaginationResponse{}
	mi := &file_cartMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCartItemsWithPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCartItemsWithPaginationResponse) ProtoMessage() {}

func (x *FindCartItemsWithPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cartMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCartItemsWithPaginationResponse.ProtoReflect.Descriptor instead.
func (*FindCartItemsWithPaginationResponse) Descriptor() ([]byte, []int) {
	return file_cartMessage_proto_rawDescGZIP(), []int{8}
}

func (x *FindCartItemsWithPaginationResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FindCartItemsWithPaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindCartItemsWithPaginationResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_cartMessage_proto protoreflect.FileDescriptor

const file_cartMessage_proto_rawDesc = "" +
	"\n" +
	"\x11cartMessage.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x01\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\tR\tproductId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x05R\x03qty\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x127\n" +
	"\tcrated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bcratedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"u\n" +
	"\x15CreateCartItemRequest\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\tR\tproductId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x05R\x03qty\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"(\n" +
	"\x16CreateCartItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x89\x01\n" +
	"\x19UpdateCartItemByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\tR\tproductId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x05R\x03qty\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\",\n" +
	"\x1aUpdateCartItemByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x15DeleteCartItemRequest\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\tR\tproductId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x16DeleteCartItemResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x86\x01\n" +
	"\"FindCartItemsWithPaginationRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"productIds\x18\x02 \x03(\tR\n" +
	"productIds\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"v\n" +
	"#FindCartItemsWithPaginationResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.proto.CartItemR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitBHZFgithub.com/ferza17/ecommerce-microservices-v2/api-gateway/model/rpc/pbb\x06proto3"

var (
	file_cartMessage_proto_rawDescOnce sync.Once
	file_cartMessage_proto_rawDescData []byte
)

func file_cartMessage_proto_rawDescGZIP() []byte {
	file_cartMessage_proto_rawDescOnce.Do(func() {
		file_cartMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cartMessage_proto_rawDesc), len(file_cartMessage_proto_rawDesc)))
	})
	return file_cartMessage_proto_rawDescData
}

var file_cartMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cartMessage_proto_goTypes = []any{
	(*CartItem)(nil),                            // 0: proto.CartItem
	(*CreateCartItemRequest)(nil),               // 1: proto.CreateCartItemRequest
	(*CreateCartItemResponse)(nil),              // 2: proto.CreateCartItemResponse
	(*UpdateCartItemByIdRequest)(nil),           // 3: proto.UpdateCartItemByIdRequest
	(*UpdateCartItemByIdResponse)(nil),          // 4: proto.UpdateCartItemByIdResponse
	(*DeleteCartItemRequest)(nil),               // 5: proto.DeleteCartItemRequest
	(*DeleteCartItemResponse)(nil),              // 6: proto.DeleteCartItemResponse
	(*FindCartItemsWithPaginationRequest)(nil),  // 7: proto.FindCartItemsWithPaginationRequest
	(*FindCartItemsWithPaginationResponse)(nil), // 8: proto.FindCartItemsWithPaginationResponse
	(*timestamppb.Timestamp)(nil),               // 9: google.protobuf.Timestamp
}
var file_cartMessage_proto_depIdxs = []int32{
	9, // 0: proto.CartItem.crated_at:type_name -> google.protobuf.Timestamp
	9, // 1: proto.CartItem.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: proto.FindCartItemsWithPaginationResponse.items:type_name -> proto.CartItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cartMessage_proto_init() }
func file_cartMessage_proto_init() {
	if File_cartMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cartMessage_proto_rawDesc), len(file_cartMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cartMessage_proto_goTypes,
		DependencyIndexes: file_cartMessage_proto_depIdxs,
		MessageInfos:      file_cartMessage_proto_msgTypes,
	}.Build()
	File_cartMessage_proto = out.File
	file_cartMessage_proto_goTypes = nil
	file_cartMessage_proto_depIdxs = nil
}
