apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: consul-local
  name: consul-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul-local
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: consul-local
    spec:
      containers:
        - args:
            - agent
            - -dev
            - -client=0.0.0.0
            - -ui
          command:
            - /bin/sh
            - -c
            - consul agent -dev -client=0.0.0.0 -ui & sleep 5 && sh /init.sh && tail -f /dev/null
          image: consul:1.10.0
          livenessProbe:
            exec:
              command:
                - consul
                - members
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          name: consul-local
          ports:
            - containerPort: 8500
              protocol: TCP
            - containerPort: 8600
              protocol: TCP
            - containerPort: 8600
              protocol: UDP
          volumeMounts:
            - mountPath: /init.sh
              name: consul-local-cm0
              subPath: init.sh
            - mountPath: /rabbitmq/init-rabbitmq.sh
              name: consul-local-cm1
              subPath: init-rabbitmq.sh
            - mountPath: /rabbitmq/init-rabbitmq-exchange.sh
              name: consul-local-cm2
              subPath: init-rabbitmq-exchange.sh
            - mountPath: /rabbitmq/init-rabbitmq-queue.sh
              name: consul-local-cm3
              subPath: init-rabbitmq-queue.sh
            - mountPath: /database/elasticsearch/init-database-elasticsearch.sh
              name: consul-local-cm4
              subPath: init-database-elasticsearch.sh
            - mountPath: /database/elasticsearch/init-database-elasticsearch-proxy.sh
              name: consul-local-cm5
              subPath: init-database-elasticsearch-proxy.sh
            - mountPath: /database/elasticsearch/health-check-elasticsearch.sh
              name: consul-local-cm6
              subPath: health-check-elasticsearch.sh
            - mountPath: /database/redis/init-database-redis.sh
              name: consul-local-cm7
              subPath: init-database-redis.sh
            - mountPath: /database/redis/health-check-redis.sh
              name: consul-local-cm8
              subPath: health-check-redis.sh
            - mountPath: /database/redis/init-database-redis-proxy.sh
              name: consul-local-cm9
              subPath: init-database-redis-proxy.sh
            - mountPath: /database/mongodb/init-database-mongodb.sh
              name: consul-local-cm10
              subPath: init-database-mongodb.sh
            - mountPath: /database/mongodb/init-database-mongodb-proxy.sh
              name: consul-local-cm11
              subPath: init-database-mongodb-proxy.sh
            - mountPath: /database/mongodb/health-check-mongodb.sh
              name: consul-local-cm12
              subPath: health-check-mongodb.sh
            - mountPath: /database/postgres/init-database-postgresql.sh
              name: consul-local-cm13
              subPath: init-database-postgresql.sh
            - mountPath: /database/postgres/init-database-postgresql-proxy.sh
              name: consul-local-cm14
              subPath: init-database-postgresql-proxy.sh
            - mountPath: /database/postgres/health-check-postgresql.sh
              name: consul-local-cm15
              subPath: health-check-postgresql.sh
            - mountPath: /smtp/init-smtp.sh
              name: consul-local-cm16
              subPath: init-smtp.sh
            - mountPath: /telemetry/init-telemetry.sh
              name: consul-local-cm17
              subPath: init-telemetry.sh
            - mountPath: /services/init-api-gateway-service.sh
              name: consul-local-cm18
              subPath: init-api-gateway-service.sh
            - mountPath: /services/init-commerce-service.sh
              name: consul-local-cm19
              subPath: init-commerce-service.sh
            - mountPath: /services/init-event-store-service.sh
              name: consul-local-cm20
              subPath: init-event-store-service.sh
            - mountPath: /services/init-notification-service.sh
              name: consul-local-cm21
              subPath: init-notification-service.sh
            - mountPath: /services/init-payment-service.sh
              name: consul-local-cm22
              subPath: init-payment-service.sh
            - mountPath: /services/init-product-service.sh
              name: consul-local-cm23
              subPath: init-product-service.sh
            - mountPath: /services/init-user-service.sh
              name: consul-local-cm24
              subPath: init-user-service.sh
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init.sh
                path: init.sh
            name: consul-local-cm0
          name: consul-local-cm0
        - configMap:
            items:
              - key: init-rabbitmq.sh
                path: init-rabbitmq.sh
            name: consul-local-cm1
          name: consul-local-cm1
        - configMap:
            items:
              - key: init-rabbitmq-exchange.sh
                path: init-rabbitmq-exchange.sh
            name: consul-local-cm2
          name: consul-local-cm2
        - configMap:
            items:
              - key: init-rabbitmq-queue.sh
                path: init-rabbitmq-queue.sh
            name: consul-local-cm3
          name: consul-local-cm3
        - configMap:
            items:
              - key: init-database-elasticsearch.sh
                path: init-database-elasticsearch.sh
            name: consul-local-cm4
          name: consul-local-cm4
        - configMap:
            items:
              - key: init-database-elasticsearch-proxy.sh
                path: init-database-elasticsearch-proxy.sh
            name: consul-local-cm5
          name: consul-local-cm5
        - configMap:
            items:
              - key: health-check-elasticsearch.sh
                path: health-check-elasticsearch.sh
            name: consul-local-cm6
          name: consul-local-cm6
        - configMap:
            items:
              - key: init-database-redis.sh
                path: init-database-redis.sh
            name: consul-local-cm7
          name: consul-local-cm7
        - configMap:
            items:
              - key: health-check-redis.sh
                path: health-check-redis.sh
            name: consul-local-cm8
          name: consul-local-cm8
        - configMap:
            items:
              - key: init-database-redis-proxy.sh
                path: init-database-redis-proxy.sh
            name: consul-local-cm9
          name: consul-local-cm9
        - configMap:
            items:
              - key: init-database-mongodb.sh
                path: init-database-mongodb.sh
            name: consul-local-cm10
          name: consul-local-cm10
        - configMap:
            items:
              - key: init-database-mongodb-proxy.sh
                path: init-database-mongodb-proxy.sh
            name: consul-local-cm11
          name: consul-local-cm11
        - configMap:
            items:
              - key: health-check-mongodb.sh
                path: health-check-mongodb.sh
            name: consul-local-cm12
          name: consul-local-cm12
        - configMap:
            items:
              - key: init-database-postgresql.sh
                path: init-database-postgresql.sh
            name: consul-local-cm13
          name: consul-local-cm13
        - configMap:
            items:
              - key: init-database-postgresql-proxy.sh
                path: init-database-postgresql-proxy.sh
            name: consul-local-cm14
          name: consul-local-cm14
        - configMap:
            items:
              - key: health-check-postgresql.sh
                path: health-check-postgresql.sh
            name: consul-local-cm15
          name: consul-local-cm15
        - configMap:
            items:
              - key: init-smtp.sh
                path: init-smtp.sh
            name: consul-local-cm16
          name: consul-local-cm16
        - configMap:
            items:
              - key: init-telemetry.sh
                path: init-telemetry.sh
            name: consul-local-cm17
          name: consul-local-cm17
        - configMap:
            items:
              - key: init-api-gateway-service.sh
                path: init-api-gateway-service.sh
            name: consul-local-cm18
          name: consul-local-cm18
        - configMap:
            items:
              - key: init-commerce-service.sh
                path: init-commerce-service.sh
            name: consul-local-cm19
          name: consul-local-cm19
        - configMap:
            items:
              - key: init-event-store-service.sh
                path: init-event-store-service.sh
            name: consul-local-cm20
          name: consul-local-cm20
        - configMap:
            items:
              - key: init-notification-service.sh
                path: init-notification-service.sh
            name: consul-local-cm21
          name: consul-local-cm21
        - configMap:
            items:
              - key: init-payment-service.sh
                path: init-payment-service.sh
            name: consul-local-cm22
          name: consul-local-cm22
        - configMap:
            items:
              - key: init-product-service.sh
                path: init-product-service.sh
            name: consul-local-cm23
          name: consul-local-cm23
        - configMap:
            items:
              - key: init-user-service.sh
                path: init-user-service.sh
            name: consul-local-cm24
          name: consul-local-cm24
