apiVersion: v1
data:
  init-product-service.sh: |-
    #!/bin/sh

    initialize_product_service() {
      echo "INIT PRODUCT SERVICE"

      ## Local
      curl --request PUT --data 'local' http://localhost:8500/v1/kv/local/services/product/ENV
      curl --request PUT --data 'product-service' http://localhost:8500/v1/kv/local/services/product/SERVICE_NAME
      curl --request PUT --data 'localhost' http://localhost:8500/v1/kv/local/services/product/RPC_HOST
      curl --request PUT --data '50055' http://localhost:8500/v1/kv/local/services/product/RPC_PORT
      ## Production
      curl --request PUT --data 'production' http://localhost:8500/v1/kv/production/services/product/ENV
      curl --request PUT --data 'product-service' http://localhost:8500/v1/kv/production/services/product/SERVICE_NAME
      curl --request PUT --data 'product-service' http://localhost:8500/v1/kv/production/services/product/RPC_HOST
      curl --request PUT --data '50055' http://localhost:8500/v1/kv/production/services/product/RPC_PORT

      echo "DONE INIT PRODUCT SERVICE"
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm27
