apiVersion: v1
data:
  health-check-rabbitmq.sh: |-
    #!/bin/sh

    rabbitmq_health_check() {
      echo "⏳ Waiting for RabbitMQ Health Check..."
    }
    rabbitmq_health_check
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm5
