apiVersion: v1
data:
  init-api-gateway-service.sh: |
    #!/bin/sh


    echo "INIT CONFIG API GATEWAY"## Local
    curl --request PUT --data 'local' http://localhost:8500/v1/kv/local/services/api-gateway/ENV
    curl --request PUT --data 'api-gateway-service' http://localhost:8500/v1/kv/local/services/api-gateway/SERVICE_NAME
    curl --request PUT --data '127.0.0.1' http://localhost:8500/v1/kv/local/services/api-gateway/HTTP_HOST
    curl --request PUT --data '3000' http://localhost:8500/v1/kv/local/services/api-gateway/HTTP_PORT
    curl --request PUT --data '127.0.0.1' http://localhost:8500/v1/kv/local/services/api-gateway/RPC_HOST
    curl --request PUT --data '50000' http://localhost:8500/v1/kv/local/services/api-gateway/RPC_PORT
    ## Production
    curl --request PUT --data 'production' http://localhost:8500/v1/kv/production/services/api-gateway/ENV
    curl --request PUT --data 'api-gateway-service' http://localhost:8500/v1/kv/production/services/api-gateway/SERVICE_NAME
    curl --request PUT --data 'api-gateway-service' http://localhost:8500/v1/kv/production/services/api-gateway/HTTP_HOST
    curl --request PUT --data '3000' http://localhost:8500/v1/kv/production/services/api-gateway/HTTP_PORT
    curl --request PUT --data 'api-gateway-service' http://localhost:8500/v1/kv/production/services/api-gateway/RPC_HOST
    curl --request PUT --data '50000' http://localhost:8500/v1/kv/production/services/api-gateway/RPC_PORT
    echo "DONE INIT CONFIG API GATEWAY"
  init-commerce-service.sh: |
    #!/bin/sh

    echo "INIT CONFIG COMMERCE-SERVICE"
    ## Local
    consul kv put local/services/commerce/ENV 'local'
    consul kv put local/services/commerce/SERVICE_NAME 'commerce-service'
    consul kv put local/services/commerce/RPC_HOST '127.0.0.1'
    consul kv put local/services/commerce/RPC_PORT '50051'
    consul kv put local/services/commerce/HTTP_HOST '127.0.0.1'
    consul kv put local/services/commerce/HTTP_PORT '40051'
    consul kv put local/services/commerce/METRIC_HTTP_PORT '30051'
    ## Production
    consul kv put production/services/commerce/ENV 'local'
    consul kv put production/services/commerce/SERVICE_NAME 'commerce-service'
    consul kv put production/services/commerce/RPC_HOST 'commerce-service'
    consul kv put production/services/commerce/RPC_PORT '50051'
    consul kv put production/services/commerce/HTTP_HOST 'commerce-service'
    consul kv put production/services/commerce/HTTP_PORT '40051'
    consul kv put production/services/commerce/METRIC_HTTP_PORT '30051'
    echo "DONE INIT CONFIG COMMERCE-SERVICE"
  init-event-store-service.sh: |
    #!/bin/sh


    echo "INIT EVENT-STORE SERVICE"## Local
    curl --request PUT --data 'local' http://localhost:8500/v1/kv/local/services/event-store/ENV
    curl --request PUT --data 'event-store-service' http://localhost:8500/v1/kv/local/services/event-store/SERVICE_NAME
    curl --request PUT --data '127.0.0.1' http://localhost:8500/v1/kv/local/services/event-store/RPC_HOST
    curl --request PUT --data '50052' http://localhost:8500/v1/kv/local/services/event-store/RPC_PORT
    ## Production
    curl --request PUT --data 'production' http://localhost:8500/v1/kv/production/services/event-store/ENV
    curl --request PUT --data 'event-store-service' http://localhost:8500/v1/kv/production/services/event-store/SERVICE_NAME
    curl --request PUT --data 'event-store-service' http://localhost:8500/v1/kv/production/services/event-store/RPC_HOST
    curl --request PUT --data '50052' http://localhost:8500/v1/kv/production/services/event-store/RPC_PORT
    echo "DONE INIT EVENT-STORE SERVICE"
  init-notification-service.sh: |
    #!/bin/sh


    echo "INIT NOTIFICATION SERVICE"
    ## Local
    consul kv put local/services/notification/ENV 'local'
    consul kv put local/services/notification/SERVICE_NAME 'notification-service'
    consul kv put local/services/notification/RPC_HOST '127.0.0.1'
    consul kv put local/services/notification/RPC_PORT '50053'
    consul kv put local/services/notification/HTTP_HOST 'localhost'
    consul kv put local/services/notification/HTTP_PORT '40053'
    consul kv put local/services/notification/METRIC_HTTP_PORT '30053'
    ## Production
    consul kv put production/services/notification/ENV 'production'
    consul kv put production/services/notification/SERVICE_NAME 'notification-service'
    consul kv put production/services/notification/RPC_HOST 'notification-service'
    consul kv put production/services/notification/RPC_PORT '50053'
    consul kv put production/services/notification/HTTP_HOST 'notification-service'
    consul kv put production/services/notification/HTTP_PORT '40053'
    consul kv put production/services/notification/METRIC_HTTP_PORT '30053'
    echo "DONE INIT NOTIFICATION SERVICE"
  init-payment-service.sh: |
    #!/bin/sh


    echo "INIT PAYMENT SERVICE"
    ## LOCAL
    consul kv put local/services/payment/ENV 'local'
    consul kv put local/services/payment/SERVICE_NAME 'payment-service'
    consul kv put local/services/payment/PAYMENT_ORDER_CANCELLED_IN_MS '600000'
    consul kv put local/services/payment/RPC_HOST 'localhost'
    consul kv put local/services/payment/RPC_PORT '50054'
    consul kv put local/services/payment/HTTP_HOST 'localhost'
    consul kv put local/services/payment/HTTP_PORT '40054'
    consul kv put local/services/payment/METRIC_HTTP_PORT '30054'
    ## PRODUCTION
    consul kv put production/services/payment/ENV 'production'
    consul kv put production/services/payment/SERVICE_NAME 'payment-service'
    consul kv put production/services/payment/PAYMENT_ORDER_CANCELLED_IN_MS '600000'
    consul kv put production/services/payment/RPC_HOST 'payment-service'
    consul kv put production/services/payment/RPC_PORT '50054'
    consul kv put production/services/payment/HTTP_HOST 'payment-service'
    consul kv put production/services/payment/HTTP_PORT '40054'
    consul kv put production/services/payment/METRIC_HTTP_PORT '30054'
    echo "DONE INIT PAYMENT SERVICE"
  init-product-service.sh: |
    #!/bin/sh


    echo "INIT PRODUCT SERVICE"
    ## Local
    consul kv put local/services/product/ENV 'local'
    consul kv put local/services/product/SERVICE_NAME 'product-service'
    consul kv put local/services/product/RPC_HOST 'localhost'
    consul kv put local/services/product/RPC_PORT '50055'
    consul kv put local/services/product/HTTP_HOST 'localhost'
    consul kv put local/services/product/HTTP_PORT '40055'
    consul kv put local/services/product/METRIC_HTTP_PORT '30055'
    ## Production
    consul kv put production/services/product/ENV 'production'
    consul kv put production/services/product/SERVICE_NAME 'product-service'
    consul kv put production/services/product/RPC_HOST 'product-service'
    consul kv put production/services/product/RPC_PORT '50055'
    consul kv put production/services/product/HTTP_HOST 'product-service'
    consul kv put production/services/product/HTTP_PORT '40055'
    consul kv put production/services/product/METRIC_HTTP_PORT '30055'
    echo "DONE INIT PRODUCT SERVICE"
  init-shipping-service.sh: |+
    #!/bin/sh


    echo "INIT SHIPPING service"

    ## LOCAL
    consul kv put local/services/shipping/ENV 'local'
    consul kv put local/services/shipping/SERVICE_NAME 'shipping-services'
    consul kv put local/services/shipping/RPC_HOST '127.0.0.1'
    consul kv put local/services/shipping/RPC_PORT '50057'
    consul kv put local/services/shipping/HTTP_HOST '127.0.0.1'
    consul kv put local/services/shipping/HTTP_PORT '40057'
    consul kv put local/services/shipping/METRIC_HTTP_PORT '30057'

    ## PRODUCTION
    consul kv put production/services/shipping/ENV 'production'
    consul kv put production/services/shipping/SERVICE_NAME 'shipping-services'
    consul kv put production/services/shipping/RPC_HOST 'shipping-services'
    consul kv put production/services/shipping/RPC_PORT '50057'
    consul kv put production/services/shipping/HTTP_HOST 'shipping-services'
    consul kv put production/services/shipping/HTTP_PORT '40057'
    consul kv put production/services/shipping/METRIC_HTTP_PORT '30057'
    echo "DONE INIT SHIPPING service"






  init-user-service.sh: |
    #!/bin/sh


    echo "INIT USER SERVICE"
    ## Local
    consul kv put local/services/user/ENV 'local'
    consul kv put local/services/user/SERVICE_NAME 'user-service'
    consul kv put local/services/user/RPC_HOST 'localhost'
    consul kv put local/services/user/RPC_PORT '50056'
    consul kv put local/services/user/HTTP_HOST 'localhost'
    consul kv put local/services/user/HTTP_PORT '40056'
    consul kv put local/services/user/METRIC_HTTP_PORT '30056'
    consul kv put local/services/user/JWT_ACCESS_TOKEN_SECRET 'ecommerce-service-v2'
    consul kv put local/services/user/JWT_ACCESS_TOKEN_EXPIRATION_TIME '1h'
    consul kv put local/services/user/JWT_REFRESH_TOKEN_SECRET 'v2-service-ecommerce'
    consul kv put local/services/user/JWT_REFRESH_TOKEN_EXPIRATION_TIME '2d'
    consul kv put local/services/user/OTP_EXPIRATION_TIME '10m'
    consul kv put local/services/user/VERIFICATION_USER_LOGIN_URL 'http://localhost:4000?access_token=%s?refresh_token=?'

    ## Production
    consul kv put production/services/user/ENV 'production'
    consul kv put production/services/user/SERVICE_NAME 'user-service'
    consul kv put production/services/user/RPC_HOST 'user-service'
    consul kv put production/services/user/RPC_PORT '50056'
    consul kv put production/services/user/HTTP_HOST 'user-service'
    consul kv put production/services/user/HTTP_PORT '40056'
    consul kv put production/services/user/METRIC_HTTP_PORT '30056'
    consul kv put production/services/user/JWT_ACCESS_TOKEN_SECRET 'ecommerce-service-v2'
    consul kv put production/services/user/JWT_ACCESS_TOKEN_EXPIRATION_TIME '1h'
    consul kv put production/services/user/JWT_REFRESH_TOKEN_SECRET 'v2-service-ecommerce'
    consul kv put production/services/user/JWT_REFRESH_TOKEN_EXPIRATION_TIME '1h'
    consul kv put production/services/user/OTP_EXPIRATION_TIME '10m'
    consul kv put production/services/user/VERIFICATION_USER_LOGIN_URL 'http://user-service:4000?access_token=%s?refresh_token=?'
    echo "DONE INIT USER SERVICE"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm4
