apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: consul-local
  name: consul-local
spec:
  ports:
    - name: "8500"
      port: 8500
      targetPort: 8500
    - name: "8600"
      port: 8600
      targetPort: 8600
    - name: 8600-udp
      port: 8600
      protocol: UDP
      targetPort: 8600
  selector:
    io.kompose.service: consul-local
