apiVersion: v1
data:
  init.sh: |
    #!/bin/sh

    echo "⏳ Waiting for Consul..."
    until curl -s http://localhost:8500/v1/status/leader | grep -q '"'; do
      sleep 1
    done


    # LOAD CONFIG RABBITMQ
    ##########################################################################################################################################################################################################################
    source /rabbitmq/init-rabbitmq.sh
    initialize_rabbitmq

    source /rabbitmq/init-rabbitmq-exchange.sh
    initialize_rabbitmq_exchange

    source /rabbitmq/init-rabbitmq-queue.sh
    initialize_rabbitmq_queue

    # LOAD CONFIG DATABASE
    ##########################################################################################################################################################################################################################
    # ELASTICSEARCH
    source /database/elasticsearch/init-database-elasticsearch.sh
    source /database/elasticsearch/init-database-elasticsearch-proxy.sh
    source /database/elasticsearch/health-check-elasticsearch.sh

    # POSTGRES
    source /database/postgres/init-database-postgresql.sh
    source /database/postgres/init-database-postgresql-proxy.sh
    source /database/postgres/health-check-postgresql.sh


    # REDIS
    source /database/redis/init-database-redis.sh
    source /database/redis/init-database-redis-proxy.sh
    source /database/redis/health-check-redis.sh

    # MONGODB
    source /database/mongodb/init-database-mongodb.sh
    source /database/mongodb/init-database-mongodb-proxy.sh
    source /database/mongodb/health-check-mongodb.sh


    # LOAD CONFIG SMTP
    ##########################################################################################################################################################################################################################
    source /smtp/init-smtp.sh
    initialize_smtp

    # LOAD CONFIG TELEMETRY
    ##########################################################################################################################################################################################################################
    source /telemetry/init-telemetry.sh
    initialize_telemetry

    # LOAD CONFIG SERVICES
    ##########################################################################################################################################################################################################################
    source /services/init-api-gateway-service.sh
    initialize_service_api_gateway

    source /services/init-commerce-service.sh
    initialize_commerce_service

    source /services/init-event-store-service.sh
    initialize_event_store_service

    source /services/init-notification-service.sh
    initialize_notification_service

    source /services/init-payment-service.sh
    initialize_payment_service

    source /services/init-product-service.sh
    initialize_product_service

    source /services/init-user-service.sh
    initialize_user_service

    ##########################################################################################################################################################################################################################

    echo "INIT CONFIG COMMON"
    ## Local
    curl --request PUT --data 'PENDING' http://localhost:8500/v1/kv/local/common/SAGA_STATUS/PENDING
    curl --request PUT --data 'SUCCESS' http://localhost:8500/v1/kv/local/common/SAGA_STATUS/SUCCESS
    curl --request PUT --data 'FAILED' http://localhost:8500/v1/kv/local/common/SAGA_STATUS/FAILED

    ## Production
    curl --request PUT --data 'PENDING' http://localhost:8500/v1/kv/production/common/SAGA_STATUS/PENDING
    curl --request PUT --data 'SUCCESS' http://localhost:8500/v1/kv/production/common/SAGA_STATUS/SUCCESS
    curl --request PUT --data 'FAILED' http://localhost:8500/v1/kv/production/common/SAGA_STATUS/FAILED

    echo "✅ Done setting key-values."
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm0
