apiVersion: v1
data:
  service_register.sh: |
    #!/bin/bash

    echo "Registering PostgresSQL Metric Exporter to Consul ..."

    # Wait for PostgresSQL Metric Exporter to be available (max 10 retries)
    echo "Waiting for PostgresSQL Metric Exporter to be available..."
    max_retries=10
    count=0

    until nc -z postgres-exporter-local 9187 >/dev/null 2>&1; do
      count=$((count+1))
      echo "PostgresSQL Metric Exporter not ready yet, attempt $count/$max_retries..."

      if [ $count -ge $max_retries ]; then
        echo "⚠️ PostgresSQL Metric Exporter still not available after $max_retries attempts, continuing anyway..."
        break
      fi
      sleep 2
    done
    echo "PostgresSQL Metric Exporter check finished"


    # Register Postgresql Exporter service
    consul services register \
    -name=PostgresSQL Exporter \
    -id=postgres-exporter-main \
    -port=9187 \
    -address=postgres-exporter-local \
    -tag=metrics \
    -tag=postgresSQL \
    -tag=PostgresSQL Exporter

    # Manual health check registration via HTTP API
    echo "Adding health checks..."

    # Health check for MongoDB
    curl -s -X PUT http://consul-local:8500/v1/agent/check/register \
    -H "Content-Type: application/json" \
    -d '{
    "ID": "PostgresSQL-Exporter-health",
    "Name": "PostgresSQL Exporter Health Check",
    "HTTP": "http://postgres-exporter-local:9187/metrics",
    "Interval": "30s",
    "Timeout": "5s",
    "ServiceID": "postgres-exporter-main"
    }'

    # Verify registration
    echo "✅ PostgresSQL Metric Exporter registration completed"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm8
