apiVersion: v1
data:
  init-product-service.sh: "#!/bin/sh\n\ninitialize_product_service() {\n  echo \"INIT PRODUCT SERVICE\"\n\n  ## Local\n  consul kv put local/services/product/ENV 'local' \n  consul kv put local/services/product/SERVICE_NAME 'product-service' \n  consul kv put local/services/product/RPC_HOST 'localhost' \n  consul kv put local/services/product/RPC_PORT '50055' \n  consul kv put local/services/product/HTTP_HOST 'localhost' \n  consul kv put local/services/product/HTTP_PORT '40055'\n  consul kv put local/services/product/METRIC_HTTP_PORT '30055'\n\n  ## Production\n  consul kv put production/services/product/ENV 'production' \n  consul kv put production/services/product/SERVICE_NAME 'product-service' \n  consul kv put production/services/product/RPC_HOST 'product-service' \n  consul kv put production/services/product/RPC_PORT '50055' \n  consul kv put production/services/product/HTTP_HOST 'product-service' \n  consul kv put production/services/product/HTTP_PORT '40055'\n  consul kv put production/services/product/METRIC_HTTP_PORT '30055'\n  echo \"DONE INIT PRODUCT SERVICE\"\n}"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm27
