apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: consul-local
  name: consul-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul-local
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: consul-local
    spec:
      containers:
        - args:
            - agent
            - -dev
            - -client=0.0.0.0
            - -ui
          command:
            - /bin/sh
            - -c
            - consul agent -dev -client=0.0.0.0 -ui & sleep 5 && sh /init.sh && tail -f /dev/null
          image: consul:1.10.0
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - consul kv get config/setup/initialized | grep -q true
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: consul-local
          ports:
            - containerPort: 8500
              protocol: TCP
            - containerPort: 8600
              protocol: TCP
            - containerPort: 8600
              protocol: UDP
          volumeMounts:
            - mountPath: /init.sh
              name: consul-local-cm0
              readOnly: true
              subPath: init.sh
            - mountPath: /prometheus
              name: consul-local-cm2
              readOnly: true
            - mountPath: /rabbitmq
              name: consul-local-cm3
              readOnly: true
            - mountPath: /services
              name: consul-local-cm4
              readOnly: true
            - mountPath: /smtp
              name: consul-local-cm5
              readOnly: true
            - mountPath: /telemetry
              name: consul-local-cm6
              readOnly: true
            - mountPath: /traefik
              name: consul-local-cm7
              readOnly: true
            - mountPath: /postgres-exporter
              name: consul-local-cm8
              readOnly: true
            - mountPath: /opa
              name: consul-local-cm9
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init.sh
                path: init.sh
            name: consul-local-cm0
          name: consul-local-cm0
        - configMap:
            name: consul-local-cm2
          name: consul-local-cm2
        - configMap:
            name: consul-local-cm3
          name: consul-local-cm3
        - configMap:
            name: consul-local-cm4
          name: consul-local-cm4
        - configMap:
            name: consul-local-cm5
          name: consul-local-cm5
        - configMap:
            name: consul-local-cm6
          name: consul-local-cm6
        - configMap:
            name: consul-local-cm7
          name: consul-local-cm7
        - configMap:
            name: consul-local-cm8
          name: consul-local-cm8
        - configMap:
            name: consul-local-cm9
          name: consul-local-cm9
