apiVersion: v1
data:
  health-check-postgresql.sh: |-
    #!/bin/bash

    postgres_health_check() {
      echo "⏳ Waiting for Postgres Health Check..."
    }
    postgres_health_check
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm17
