apiVersion: v1
data:
  init-telemetry.sh: |-
    #!/bin/sh

    initialize_telemetry(){
      echo "INIT CONFIG TELEMETRY"
      # Jaeger Local
      consul kv put local/telemetry/jaeger/JAEGER_TELEMETRY_HOST "localhost"
      consul kv put local/telemetry/jaeger/JAEGER_TELEMETRY_PORT "14268"

      # Jaeger Production
      consul kv put production/telemetry/jaeger/JAEGER_TELEMETRY_HOST "jaeger-local"
      consul kv put production/telemetry/jaeger/JAEGER_TELEMETRY_PORT "14268"

      echo "DONE INIT CONFIG TELEMETRY"
    }

    initialize_telemetry
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm20
