apiVersion: v1
data:
  init-rabbitmq.sh: |-
    #!/bin/sh

    initialize_rabbitmq () {
      echo "INIT CONFIG RABBITMQ"
      ## Local
      curl --request PUT --data 'rabbitmq' http://localhost:8500/v1/kv/local/broker/rabbitmq/RABBITMQ_USERNAME
      curl --request PUT --data '1234' http://localhost:8500/v1/kv/local/broker/rabbitmq/RABBITMQ_PASSWORD
      curl --request PUT --data 'localhost' http://localhost:8500/v1/kv/local/broker/rabbitmq/RABBITMQ_HOST
      curl --request PUT --data '5672' http://localhost:8500/v1/kv/local/broker/rabbitmq/RABBITMQ_PORT
      ## Production
      curl --request PUT --data 'rabbitmq' http://localhost:8500/v1/kv/production/broker/rabbitmq/RABBITMQ_USERNAME
      curl --request PUT --data '1234' http://localhost:8500/v1/kv/production/broker/rabbitmq/RABBITMQ_PASSWORD
      curl --request PUT --data 'rabbitmq-local' http://localhost:8500/v1/kv/production/broker/rabbitmq/RABBITMQ_HOST
      curl --request PUT --data '5672' http://localhost:8500/v1/kv/production/broker/rabbitmq/RABBITMQ_PORT

      echo "DONE INIT CONFIG RABBITMQ"
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm1
