apiVersion: v1
data:
  init-user-service.sh: |-
    #!/bin/sh

    initialize_user_service(){
      echo "INIT USER SERVICE"
      ## Local
      curl --request PUT --data 'local' http://localhost:8500/v1/kv/local/services/user/ENV
      curl --request PUT --data 'user-service' http://localhost:8500/v1/kv/local/services/user/SERVICE_NAME
      curl --request PUT --data 'localhost' http://localhost:8500/v1/kv/local/services/user/RPC_HOST
      curl --request PUT --data '50056' http://localhost:8500/v1/kv/local/services/user/RPC_PORT
      curl --request PUT --data 'ecommerce-service-v2' http://localhost:8500/v1/kv/local/services/user/JWT_ACCESS_TOKEN_SECRET
      curl --request PUT --data '1h' http://localhost:8500/v1/kv/local/services/user/JWT_ACCESS_TOKEN_EXPIRATION_TIME
      curl --request PUT --data 'v2-service-ecommerce' http://localhost:8500/v1/kv/local/services/user/JWT_REFRESH_TOKEN_SECRET
      curl --request PUT --data '2d' http://localhost:8500/v1/kv/local/services/user/JWT_REFRESH_TOKEN_EXPIRATION_TIME
      curl --request PUT --data '10m' http://localhost:8500/v1/kv/local/services/user/OTP_EXPIRATION_TIME
      curl --request PUT --data 'http://localhost:4000?access_token=%s?refresh_token=?' http://localhost:8500/v1/kv/local/services/user/VERIFICATION_USER_LOGIN_URL
      ## Production
      curl --request PUT --data 'production' http://localhost:8500/v1/kv/production/services/user/ENV
      curl --request PUT --data 'user-service' http://localhost:8500/v1/kv/production/services/user/SERVICE_NAME
      curl --request PUT --data 'user-service' http://localhost:8500/v1/kv/production/services/user/RPC_HOST
      curl --request PUT --data '50056' http://localhost:8500/v1/kv/production/services/user/RPC_PORT
      curl --request PUT --data 'ecommerce-service-v2' http://localhost:8500/v1/kv/production/services/user/JWT_ACCESS_TOKEN_SECRET
      curl --request PUT --data '1h' http://localhost:8500/v1/kv/production/services/user/JWT_ACCESS_TOKEN_EXPIRATION_TIME
      curl --request PUT --data 'v2-service-ecommerce' http://localhost:8500/v1/kv/production/services/user/JWT_REFRESH_TOKEN_SECRET
      curl --request PUT --data '2d' http://localhost:8500/v1/kv/production/services/user/JWT_REFRESH_TOKEN_EXPIRATION_TIME
      curl --request PUT --data '1m' http://localhost:8500/v1/kv/production/services/user/OTP_EXPIRATION_TIME
      curl --request PUT --data 'http://localhost:4000?access_token=%s?refresh_token=?' http://localhost:8500/v1/kv/production/services/user/VERIFICATION_USER_LOGIN_URL

      echo "DONE INIT USER SERVICE"
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consul-local
  name: consul-local-cm28
