apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: event-store-service
  name: event-store-service
spec:
  ports:
    - name: "50052"
      port: 50052
      targetPort: 50052
    - name: "40052"
      port: 40052
      targetPort: 40052
    - name: "30052"
      port: 30052
      targetPort: 30052
  selector:
    io.kompose.service: event-store-service
