apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: grafana-local
  name: grafana-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-local
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: grafana-local
    spec:
      containers:
        - env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "12345"
            - name: GF_SECURITY_ADMIN_USER
              value: grafana
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          image: grafana/grafana:latest
          name: grafana-local
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
