apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: keyfile-gen
  name: keyfile-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keyfile-gen
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: keyfile-gen
    spec:
      containers:
        - args:
            - ' apk add --no-cache openssl && openssl rand -base64 741 > /data/mongodb.key && chmod 600 /data/mongodb.key && chown 999:999 /data/mongodb.key && tail -f /dev/null'
          command:
            - sh
            - -c
          image: alpine
          livenessProbe:
            exec:
              command:
                - '[ -f /data/mongodb.key ] && [ -s /data/mongodb.key ] || exit 1'
            failureThreshold: 10
            periodSeconds: 2
            timeoutSeconds: 5
          name: keyfile-gen
          volumeMounts:
            - mountPath: /data
              name: keyfile-gen-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: keyfile-gen-cm0
          name: keyfile-gen-cm0
