apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mailhog-local
  name: mailhog-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailhog-local
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: mailhog-local
    spec:
      containers:
        - image: mailhog/mailhog:latest
          name: mailhog-local
          ports:
            - containerPort: 1025
              protocol: TCP
            - containerPort: 8025
              protocol: TCP
      restartPolicy: Always
