apiVersion: v1
data:
  mongo-init.js: |2
    // Create databases & collections
    print("Creating database notifications & collections...");
    db = db.getSiblingDB('notification');
    db.createUser({
        user: "mongo",
        pwd: "1234",
        roles: [{ role: "readWrite", db: "notification" }]
    });
    db.createCollection('notification_templates');

    print("Creating database commerce & collections...");
    db = db.getSiblingDB('commerce');
    db.createUser({
        user: "mongo",
        pwd: "1234",
        roles: [{ role: "readWrite", db: "commerce" }]
    });
    db.createCollection('carts');
    db.createCollection('wishlists');

    print("Creating database commerce & collections...");
    db = db.getSiblingDB('event');
    db.createUser({
        user: "mongo",
        pwd: "1234",
        roles: [{ role: "readWrite", db: "commerce" }]
    });
    db.createCollection('user-event-stores');
    db.createCollection('notification-event-stores');
    db.createCollection('payment-event-stores');
    db.createCollection('product-event-stores');
    db.createCollection('shipping-event-stores');
    db.createCollection('commerce-event-stores');
  mongodb.key: |
    eBdICLGgzv+GU2SNG9WVRLgWr1/yK/nkOrtGAS0rVJcuI3v4XdKhkFb4ncIMgy6L
    C4Ba8y7eXLupqHbyQC+A8AdUSxBNDLPFMqk9nW9Qk4YzvDvhJHPE3qjIV+dePUq2
    YpyP+mVyf/jp1O2mVrMonOO+DZwzLR6C8Wrz76GhIalYYNyBy/gdjeX3YXnw1WlC
    SFfBui0XzATTPfAVW3IJ6lZrbXVFoNP/12MYSlOoZj4PWqEcuAaslrGZrUdzu8BZ
    ivU13i1o61wf5ABUkdCNMTzzPApQV9HXfG+WdE+SVEzNn2hkKfZkL2lTQExeDeN4
    ajj9TNHV0ZV7ESjjsQsg3f+9qlqaewtTh+jI8ksYAwP3FUF8Gem0/miPfUQ5uITY
    HW7Zo79D/fbWycOVoaYdQ4qPsxx+xAxgnXByrHAWyTNwSTGiW5zPJ31ENzWGDfX7
    wYncJCL1OgfT8GlKISI1PBO1qaUav/P6A9/MjU2gyN28oqzS6jmxeOsfQJYu49Rj
    yYzYDJMT579fNV9LEimoV47mjKalwizP79PqGgwiMhYjtvbrKEtKrbDGRLcY/X/Z
    X8KeoNVNJh42xnkmoqS8xzUpyTn+PISOfKxmMiPXbocVWFTEH3Mxugavws9aMQhw
    pQ6fvlmHc4ALZMBzK3OPvzsD+5r+2eXot3O0JTo6H7ce8gi1Hlbx84psh1buQ/Gh
    1e2zML2XQgOGEoR9Gs3hn4V+xtQ5Ryn+hZ+lzOpvyEkCFQ/NGg/wdOZAyeI1Me30
    suPtHVdi7XWV0cQ9/HJLbTbQtHbcZ1QNgPhjHFz7DDr5QYLfKK0IygAcILGNiUbG
    xKV9Gns+qfEJ3KbU/wPSOALtfSa++CmJlV1ms6jI7rTbQ0w12ahKAVCjjI7Uo5+e
    NAKV9TT8VcwuTPWWcb5S8+FikqMt5ubf0YO0lE/HUL31TgHd1V0zbHZDV1GwYdvR
    j3Xn8j+oFO2J2sMA5YDVRhfBgdLP
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: mongo-local
  name: mongo-local-cm0
