apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: opa-local
  name: opa-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opa-local
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: opa-local
    spec:
      containers:
        - args:
            - run
            - --server
            - --log-level=debug
            - --addr=0.0.0.0:8181
            - /policies
          env:
            - name: OPA_LOG_LEVEL
              value: debug
          image: openpolicyagent/opa:latest
          livenessProbe:
            exec:
              command:
                - curl -s -o /dev/null -w '%{http_code}' http://opa-local:8181/health | grep -q '^200$'
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: opa-local
          ports:
            - containerPort: 8181
              protocol: TCP
          volumeMounts:
            - mountPath: /policies
              name: opa-local-cm0
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: opa-local-cm0
          name: opa-local-cm0
