apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: payment-service
    spec:
      containers:
        - image: payment-service
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - payment-service:40055/v1/payment/check
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: payment-service
          ports:
            - containerPort: 50054
              protocol: TCP
            - containerPort: 40054
              protocol: TCP
            - containerPort: 30054
              protocol: TCP
      restartPolicy: Always
