apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: postgres-exporter-local
  name: postgres-exporter-local
spec:
  ports:
    - name: "9187"
      port: 9187
      targetPort: 9187
  selector:
    io.kompose.service: postgres-exporter-local
