apiVersion: v1
data:
  postgresql-initdb.sh: |
    #!/bin/sh
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE DATABASE products;
      CREATE DATABASE users;
      CREATE DATABASE payments;
    EOSQL
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres-local
  name: postgres-local-cm0
