apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: product-service
    spec:
      containers:
        - image: product-service
          livenessProbe:
            exec:
              command:
                - curl -s -o /dev/null -w '%{http_code}' http://product-service:40055/v1/product/check | grep -q '^200$'
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: product-service
          ports:
            - containerPort: 50055
              protocol: TCP
            - containerPort: 40055
              protocol: TCP
            - containerPort: 30055
              protocol: TCP
      restartPolicy: Always
