apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  ports:
    - name: "50055"
      port: 50055
      targetPort: 50055
    - name: "40055"
      port: 40055
      targetPort: 40055
    - name: "30055"
      port: 30055
      targetPort: 30055
  selector:
    io.kompose.service: product-service
