apiVersion: v1
data:
  prometheus.yml: |2-
    global:
      scrape_interval: 30s
      evaluation_interval: 30s

    rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"

    scrape_configs:
      # Prometheus self-monitoring
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus-local:9090']

      # Jaeger metrics scraping
      - job_name: 'jaeger'
        static_configs:
          - targets: ['jaeger-local:14269']
        scrape_interval: 30s
        metrics_path: /metrics

      # POSTGRESQL METRICS EXPORTER
      - job_name: 'postgresql'
        static_configs:
          - targets: [ 'postgres-exporter-local:9187' ]
        scrape_interval: 30s
        metrics_path: /metrics

      - job_name: 'user-service-metrics'
        static_configs:
          - targets: [ 'user-service:30056' ]
        scrape_interval: 30s
        metrics_path: /v1/user/metrics

      - job_name: 'notification-service-metrics'
        static_configs:
          - targets: [ 'notification-service:30053' ]
        scrape_interval: 30s
        metrics_path: /v1/notification/metrics

      - job_name: 'product-service-metrics'
        static_configs:
          - targets: [ 'product-service:30055' ]
        scrape_interval: 30s
        metrics_path: /v1/product/metrics

      - job_name: 'payment-service-metrics'
        static_configs:
          - targets: [ 'payment-service:30054' ]
        scrape_interval: 30s
        metrics_path: /v1/payment/metrics
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus-local
  name: prometheus-local-cm0
