apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: rabbitmq-local
  name: rabbitmq-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq-local
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: rabbitmq-local
    spec:
      containers:
        - args:
            - sh
            - -c
            - ' cp /usr/lib/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.11.1.ez /plugins/ && rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange && rabbitmq-server '
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: "1234"
            - name: RABBITMQ_DEFAULT_USER
              value: rabbitmq
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
          image: rabbitmq:3.11-management
          name: rabbitmq-local
          ports:
            - containerPort: 15672
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/lib/rabbitmq/plugins
              name: rabbitmq-local-cm0
            - mountPath: /etc/rabbitmq/definitions.json
              name: rabbitmq-local-cm1
              subPath: definitions.json
      restartPolicy: Always
      volumes:
        - configMap:
            name: rabbitmq-local-cm0
          name: rabbitmq-local-cm0
        - configMap:
            items:
              - key: definitions.json
                path: definitions.json
            name: rabbitmq-local-cm1
          name: rabbitmq-local-cm1
