apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - image: user-service
          livenessProbe:
            exec:
              command:
                - curl -s -o /dev/null -w '%{http_code}' http://user-service:40056/v1/user/check | grep -q '^200$'
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
          name: user-service
          ports:
            - containerPort: 50056
              protocol: TCP
            - containerPort: 40056
              protocol: TCP
            - containerPort: 30056
              protocol: TCP
      restartPolicy: Always
