// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rabbitmq

import (
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/rabbitmq"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/pkg/logger"
)

// Injectors from wire.go:

// ProvideRabbitMQServer initializes a rabbitMQServer using Wire.
func ProvideRabbitMQServer() IRabbitMQServer {
	iZapLogger := logger.ProvideLogger()
	iRabbitMQInfrastructure := rabbitmq.ProvideRabbitMQInfrastructure(iZapLogger)
	iRabbitMQServer := NewRabbitMQServer(iRabbitMQInfrastructure, iZapLogger)
	return iRabbitMQServer
}
