// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package presenter

import (
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/telemetry"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/module/payment/usecase"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/pkg/logger"
)

// Injectors from wire.go:

// ProvidePaymentPresenter wires dependencies for IPaymentPresenter.
func ProvidePaymentPresenter() IPaymentPresenter {
	iPaymentUseCase := usecase.ProvidePaymentUseCase()
	iZapLogger := logger.NewZapLogger()
	iTelemetryInfrastructure := telemetry.NewTelemetry(iZapLogger)
	iPaymentPresenter := NewPaymentPresenter(iPaymentUseCase, iTelemetryInfrastructure, iZapLogger)
	return iPaymentPresenter
}
