pub mod config;
mod service_api_gateway;
mod service_payment;
mod service_shipping;
mod service_user;
mod service_product;
mod telemetry_jaeger;
mod open_policy_agent;
mod service_event;
mod message_broker_kafka;
mod service_user_kafka;
