// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: cartMessage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "proto";

export interface CartItem {
  id: string;
  productId: string;
  userId: string;
  qty: number;
  price: number;
  cratedAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface CreateCartItemRequest {
  productId: string;
  userId: string;
  qty: number;
  price: number;
}

export interface CreateCartItemResponse {
  id: string;
}

export interface UpdateCartItemByIdRequest {
  id: string;
  productId: string;
  userId: string;
  qty: number;
  price: number;
}

export interface UpdateCartItemByIdResponse {
  id: string;
}

export interface FindCartItemsWithPaginationRequest {
  userId: string;
  productIds: string[];
  page: number;
  limit: number;
}

export interface FindCartItemsWithPaginationResponse {
  items: CartItem[];
  page: number;
  limit: number;
  total: number;
}

export interface FindCartItemByIdRequest {
  id: string;
}

export interface DeleteCartItemByIdRequest {
  id: string;
}

export interface DeleteCartItemByIdResponse {
  message: string;
}

function createBaseCartItem(): CartItem {
  return { id: "", productId: "", userId: "", qty: 0, price: 0, cratedAt: undefined, updatedAt: undefined };
}

export const CartItem: MessageFns<CartItem> = {
  encode(message: CartItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.productId !== "") {
      writer.uint32(18).string(message.productId);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.qty !== 0) {
      writer.uint32(32).int32(message.qty);
    }
    if (message.price !== 0) {
      writer.uint32(41).double(message.price);
    }
    if (message.cratedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.cratedAt), writer.uint32(50).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CartItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCartItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.qty = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cratedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CartItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      qty: isSet(object.qty) ? globalThis.Number(object.qty) : 0,
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      cratedAt: isSet(object.cratedAt) ? fromJsonTimestamp(object.cratedAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: CartItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.qty !== 0) {
      obj.qty = Math.round(message.qty);
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.cratedAt !== undefined) {
      obj.cratedAt = message.cratedAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<CartItem>): CartItem {
    return CartItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CartItem>): CartItem {
    const message = createBaseCartItem();
    message.id = object.id ?? "";
    message.productId = object.productId ?? "";
    message.userId = object.userId ?? "";
    message.qty = object.qty ?? 0;
    message.price = object.price ?? 0;
    message.cratedAt = object.cratedAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseCreateCartItemRequest(): CreateCartItemRequest {
  return { productId: "", userId: "", qty: 0, price: 0 };
}

export const CreateCartItemRequest: MessageFns<CreateCartItemRequest> = {
  encode(message: CreateCartItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.qty !== 0) {
      writer.uint32(24).int32(message.qty);
    }
    if (message.price !== 0) {
      writer.uint32(33).double(message.price);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCartItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCartItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.qty = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.price = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCartItemRequest {
    return {
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      qty: isSet(object.qty) ? globalThis.Number(object.qty) : 0,
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
    };
  },

  toJSON(message: CreateCartItemRequest): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.qty !== 0) {
      obj.qty = Math.round(message.qty);
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateCartItemRequest>): CreateCartItemRequest {
    return CreateCartItemRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateCartItemRequest>): CreateCartItemRequest {
    const message = createBaseCreateCartItemRequest();
    message.productId = object.productId ?? "";
    message.userId = object.userId ?? "";
    message.qty = object.qty ?? 0;
    message.price = object.price ?? 0;
    return message;
  },
};

function createBaseCreateCartItemResponse(): CreateCartItemResponse {
  return { id: "" };
}

export const CreateCartItemResponse: MessageFns<CreateCartItemResponse> = {
  encode(message: CreateCartItemResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCartItemResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCartItemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCartItemResponse {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: CreateCartItemResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateCartItemResponse>): CreateCartItemResponse {
    return CreateCartItemResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateCartItemResponse>): CreateCartItemResponse {
    const message = createBaseCreateCartItemResponse();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseUpdateCartItemByIdRequest(): UpdateCartItemByIdRequest {
  return { id: "", productId: "", userId: "", qty: 0, price: 0 };
}

export const UpdateCartItemByIdRequest: MessageFns<UpdateCartItemByIdRequest> = {
  encode(message: UpdateCartItemByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.productId !== "") {
      writer.uint32(18).string(message.productId);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.qty !== 0) {
      writer.uint32(32).int32(message.qty);
    }
    if (message.price !== 0) {
      writer.uint32(41).double(message.price);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateCartItemByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateCartItemByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.qty = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.price = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateCartItemByIdRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      qty: isSet(object.qty) ? globalThis.Number(object.qty) : 0,
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
    };
  },

  toJSON(message: UpdateCartItemByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.qty !== 0) {
      obj.qty = Math.round(message.qty);
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateCartItemByIdRequest>): UpdateCartItemByIdRequest {
    return UpdateCartItemByIdRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateCartItemByIdRequest>): UpdateCartItemByIdRequest {
    const message = createBaseUpdateCartItemByIdRequest();
    message.id = object.id ?? "";
    message.productId = object.productId ?? "";
    message.userId = object.userId ?? "";
    message.qty = object.qty ?? 0;
    message.price = object.price ?? 0;
    return message;
  },
};

function createBaseUpdateCartItemByIdResponse(): UpdateCartItemByIdResponse {
  return { id: "" };
}

export const UpdateCartItemByIdResponse: MessageFns<UpdateCartItemByIdResponse> = {
  encode(message: UpdateCartItemByIdResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateCartItemByIdResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateCartItemByIdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateCartItemByIdResponse {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: UpdateCartItemByIdResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateCartItemByIdResponse>): UpdateCartItemByIdResponse {
    return UpdateCartItemByIdResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateCartItemByIdResponse>): UpdateCartItemByIdResponse {
    const message = createBaseUpdateCartItemByIdResponse();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseFindCartItemsWithPaginationRequest(): FindCartItemsWithPaginationRequest {
  return { userId: "", productIds: [], page: 0, limit: 0 };
}

export const FindCartItemsWithPaginationRequest: MessageFns<FindCartItemsWithPaginationRequest> = {
  encode(message: FindCartItemsWithPaginationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    for (const v of message.productIds) {
      writer.uint32(18).string(v!);
    }
    if (message.page !== 0) {
      writer.uint32(24).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindCartItemsWithPaginationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindCartItemsWithPaginationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.productIds.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindCartItemsWithPaginationRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      productIds: globalThis.Array.isArray(object?.productIds)
        ? object.productIds.map((e: any) => globalThis.String(e))
        : [],
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: FindCartItemsWithPaginationRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.productIds?.length) {
      obj.productIds = message.productIds;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create(base?: DeepPartial<FindCartItemsWithPaginationRequest>): FindCartItemsWithPaginationRequest {
    return FindCartItemsWithPaginationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindCartItemsWithPaginationRequest>): FindCartItemsWithPaginationRequest {
    const message = createBaseFindCartItemsWithPaginationRequest();
    message.userId = object.userId ?? "";
    message.productIds = object.productIds?.map((e) => e) || [];
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseFindCartItemsWithPaginationResponse(): FindCartItemsWithPaginationResponse {
  return { items: [], page: 0, limit: 0, total: 0 };
}

export const FindCartItemsWithPaginationResponse: MessageFns<FindCartItemsWithPaginationResponse> = {
  encode(message: FindCartItemsWithPaginationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      CartItem.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.total !== 0) {
      writer.uint32(32).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindCartItemsWithPaginationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindCartItemsWithPaginationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(CartItem.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindCartItemsWithPaginationResponse {
    return {
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => CartItem.fromJSON(e)) : [],
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: FindCartItemsWithPaginationResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => CartItem.toJSON(e));
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create(base?: DeepPartial<FindCartItemsWithPaginationResponse>): FindCartItemsWithPaginationResponse {
    return FindCartItemsWithPaginationResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindCartItemsWithPaginationResponse>): FindCartItemsWithPaginationResponse {
    const message = createBaseFindCartItemsWithPaginationResponse();
    message.items = object.items?.map((e) => CartItem.fromPartial(e)) || [];
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseFindCartItemByIdRequest(): FindCartItemByIdRequest {
  return { id: "" };
}

export const FindCartItemByIdRequest: MessageFns<FindCartItemByIdRequest> = {
  encode(message: FindCartItemByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindCartItemByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindCartItemByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindCartItemByIdRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: FindCartItemByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<FindCartItemByIdRequest>): FindCartItemByIdRequest {
    return FindCartItemByIdRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindCartItemByIdRequest>): FindCartItemByIdRequest {
    const message = createBaseFindCartItemByIdRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDeleteCartItemByIdRequest(): DeleteCartItemByIdRequest {
  return { id: "" };
}

export const DeleteCartItemByIdRequest: MessageFns<DeleteCartItemByIdRequest> = {
  encode(message: DeleteCartItemByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCartItemByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCartItemByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCartItemByIdRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteCartItemByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteCartItemByIdRequest>): DeleteCartItemByIdRequest {
    return DeleteCartItemByIdRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteCartItemByIdRequest>): DeleteCartItemByIdRequest {
    const message = createBaseDeleteCartItemByIdRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDeleteCartItemByIdResponse(): DeleteCartItemByIdResponse {
  return { message: "" };
}

export const DeleteCartItemByIdResponse: MessageFns<DeleteCartItemByIdResponse> = {
  encode(message: DeleteCartItemByIdResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCartItemByIdResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCartItemByIdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCartItemByIdResponse {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: DeleteCartItemByIdResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteCartItemByIdResponse>): DeleteCartItemByIdResponse {
    return DeleteCartItemByIdResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteCartItemByIdResponse>): DeleteCartItemByIdResponse {
    const message = createBaseDeleteCartItemByIdResponse();
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
