// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/kafka"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/mongodb"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/postgresql"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/service/product"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/service/shipping"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/service/user"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/infrastructure/telemetry"
	mongodb2 "github.com/ferza17/ecommerce-microservices-v2/payment-service/module/event/repository/mongodb"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/module/event/usecase"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/module/payment/presenter"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/module/payment/repository"
	usecase2 "github.com/ferza17/ecommerce-microservices-v2/payment-service/module/payment/usecase"
	presenter2 "github.com/ferza17/ecommerce-microservices-v2/payment-service/module/provider/presenter"
	repository2 "github.com/ferza17/ecommerce-microservices-v2/payment-service/module/provider/repository"
	usecase3 "github.com/ferza17/ecommerce-microservices-v2/payment-service/module/provider/usecase"
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/pkg/logger"
)

// Injectors from wire.go:

func Provide() *Transport {
	iZapLogger := logger.NewZapLogger()
	postgresSQL := postgresql.NewPostgresqlInfrastructure(iZapLogger)
	iTelemetryInfrastructure := telemetry.NewTelemetry(iZapLogger)
	iPaymentRepository := repository.NewPaymentRepository(postgresSQL, iTelemetryInfrastructure, iZapLogger)
	iPaymentProviderRepository := repository2.NewPaymentProviderRepository(postgresSQL, iTelemetryInfrastructure, iZapLogger)
	iKafkaInfrastructure := kafka.NewKafkaInfrastructure(iZapLogger, iTelemetryInfrastructure)
	iShippingService := shipping.NewShippingService(iZapLogger)
	iUserService := user.NewUserService(iZapLogger)
	iProductService := product.NewProductService(iZapLogger)
	iMongoDBInfrastructure := mongodb.NewMongoDBInfrastructure(iZapLogger)
	iEventMongoRepository := mongodb2.NewEventMongoDBRepository(iMongoDBInfrastructure, iTelemetryInfrastructure, iZapLogger)
	iEventUseCase := usecase.NewEventUseCase(iEventMongoRepository, iKafkaInfrastructure, iTelemetryInfrastructure)
	iPaymentUseCase := usecase2.NewPaymentUseCase(iPaymentRepository, iPaymentProviderRepository, iKafkaInfrastructure, iTelemetryInfrastructure, iZapLogger, postgresSQL, iShippingService, iUserService, iProductService, iEventMongoRepository, iEventUseCase)
	iPaymentPresenter := presenter.NewPaymentPresenter(iPaymentUseCase, iTelemetryInfrastructure, iUserService, iZapLogger)
	iPaymentProviderUseCase := usecase3.NewPaymentProviderUseCase(iPaymentProviderRepository, iKafkaInfrastructure, iTelemetryInfrastructure, postgresSQL, iZapLogger)
	iPaymentProviderPresenter := presenter2.NewPaymentProviderPresenter(iPaymentProviderUseCase, iTelemetryInfrastructure, iUserService, iZapLogger)
	transport := NewTransport(iZapLogger, iPaymentPresenter, iPaymentProviderPresenter, iTelemetryInfrastructure, iUserService)
	return transport
}
