// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/pkg/logger"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

// ProvideGrpcServer initializes a GrpcServer instance using Wire and returns it as an IGrpcServer.
func ProvideGrpcServer(options ...grpc.ServerOption) IGrpcServer {
	iZapLogger := logger.ProvideLogger()
	iGrpcServer := NewGrpcServer(iZapLogger, options...)
	return iGrpcServer
}
