// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package circuit

import (
	"github.com/ferza17/ecommerce-microservices-v2/payment-service/pkg/logger"
)

// Injectors from wire.go:

// InitializeCircuitBreaker is the Wire injector function
// that provides an instance of ICircuitBreaker.
func InitializeCircuitBreaker(svcName string, logger2 logger.IZapLogger) ICircuitBreaker {
	iCircuitBreaker := NewCircuitBreaker(svcName, logger2)
	return iCircuitBreaker
}
