// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/ferza17/ecommerce-microservices-v2/notification-service/infrastructure/temporal"
	"github.com/ferza17/ecommerce-microservices-v2/notification-service/pkg/logger"
)

// Injectors from wire.go:

func ProvideGrpcServer() *GrpcServer {
	iZapLogger := logger.NewZapLogger()
	iTemporalInfrastructure := temporal.NewTemporalInfrastructure(iZapLogger)
	grpcServer := NewGrpcServer(iTemporalInfrastructure, iZapLogger)
	return grpcServer
}
