# commerce-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commerce-service
  template:
    metadata:
      labels:
        app: commerce-service
    spec:
      containers:
        - name: commerce-service
          image: commerce-service:latest
          ports:
            - containerPort: 8001

---
# commerce-service Service
apiVersion: v1
kind: Service
metadata:
  name: commerce-service
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: commerce-service
  type: ClusterIP