# event-store-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-store-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-store-service
  template:
    metadata:
      labels:
        app: event-store-service
    spec:
      containers:
        - name: event-store-service
          image: event-store-service:latest
          ports:
            - containerPort: 8002

---
# event-store-service Service
apiVersion: v1
kind: Service
metadata:
  name: event-store-service
spec:
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: event-store-service
  type: ClusterIP
