# payment-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          ports:
            - containerPort: 8004
---
# payment-service Service
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: payment-service
  type: ClusterIP