# product-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:latest
          ports:
            - containerPort: 8005
---
# product-service Service
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
    - port: 8005
      targetPort: 8005
  selector:
    app: product-service
  type: ClusterIP
