[package]
name = "shipping-service"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/main.rs"

[build-dependencies]
tonic-build = "0.12"

[dependencies]
# CLI
clap = { version = "4", features = ["derive"] }

# LOG
log = "0.4.27"

# ASYNC AND MULTITHREAD
tokio = { version = "1.38", features = ["full"] }
tokio-util = "0.7.15"
num_cpus = "1.17.0"

# CONFIG
config = { version = "0.15.13", features = ["toml"] }
serde = { version = "1.0.219", features = ["derive"] }
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }

# CONSUL
consulrs = "0.1.0"

# PROMETHEUS METRIC
prometheus = "0.14.0"
once_cell = "1.21.3"

# DEPENDNCY INJECTION
nject = "0.4"

# ORM
diesel = { version = "2.2.0", features = ["postgres"] }

# LOGGER
tracing = "0.1.41"

# GRPC SERVER
tonic = "0.12.3"
prost = "0.13.5"
prost-types = "0.13"

# UUID
uuid = { version = "1.17.0", features = ["v4"] }

## DATABASE
tokio-postgres = "0.7.13"