// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: productServices.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_productServices_proto protoreflect.FileDescriptor

const file_productServices_proto_rawDesc = "" +
	"\n" +
	"\x15productServices.proto\x12\x05proto\x1a\x14productMessage.proto2\xaf\x03\n" +
	"\x0eProductService\x12q\n" +
	"\x1aFindProductsWithPagination\x12(.proto.FindProductsWithPaginationRequest\x1a).proto.FindProductsWithPaginationResponse\x12@\n" +
	"\x0fFindProductById\x12\x1d.proto.FindProductByIdRequest\x1a\x0e.proto.Product\x12J\n" +
	"\rCreateProduct\x12\x1b.proto.CreateProductRequest\x1a\x1c.proto.CreateProductResponse\x12D\n" +
	"\x11UpdateProductById\x12\x1f.proto.UpdateProductByIdRequest\x1a\x0e.proto.Product\x12V\n" +
	"\x11DeleteProductById\x12\x1f.proto.DeleteProductByIdRequest\x1a .proto.DeleteProductByIdResponseBHZFgithub.com/ferza17/ecommerce-microservices-v2/product-service/model/pbb\x06proto3"

var file_productServices_proto_goTypes = []any{
	(*FindProductsWithPaginationRequest)(nil),  // 0: proto.FindProductsWithPaginationRequest
	(*FindProductByIdRequest)(nil),             // 1: proto.FindProductByIdRequest
	(*CreateProductRequest)(nil),               // 2: proto.CreateProductRequest
	(*UpdateProductByIdRequest)(nil),           // 3: proto.UpdateProductByIdRequest
	(*DeleteProductByIdRequest)(nil),           // 4: proto.DeleteProductByIdRequest
	(*FindProductsWithPaginationResponse)(nil), // 5: proto.FindProductsWithPaginationResponse
	(*Product)(nil),                            // 6: proto.Product
	(*CreateProductResponse)(nil),              // 7: proto.CreateProductResponse
	(*DeleteProductByIdResponse)(nil),          // 8: proto.DeleteProductByIdResponse
}
var file_productServices_proto_depIdxs = []int32{
	0, // 0: proto.ProductService.FindProductsWithPagination:input_type -> proto.FindProductsWithPaginationRequest
	1, // 1: proto.ProductService.FindProductById:input_type -> proto.FindProductByIdRequest
	2, // 2: proto.ProductService.CreateProduct:input_type -> proto.CreateProductRequest
	3, // 3: proto.ProductService.UpdateProductById:input_type -> proto.UpdateProductByIdRequest
	4, // 4: proto.ProductService.DeleteProductById:input_type -> proto.DeleteProductByIdRequest
	5, // 5: proto.ProductService.FindProductsWithPagination:output_type -> proto.FindProductsWithPaginationResponse
	6, // 6: proto.ProductService.FindProductById:output_type -> proto.Product
	7, // 7: proto.ProductService.CreateProduct:output_type -> proto.CreateProductResponse
	6, // 8: proto.ProductService.UpdateProductById:output_type -> proto.Product
	8, // 9: proto.ProductService.DeleteProductById:output_type -> proto.DeleteProductByIdResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_productServices_proto_init() }
func file_productServices_proto_init() {
	if File_productServices_proto != nil {
		return
	}
	file_productMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_productServices_proto_rawDesc), len(file_productServices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_productServices_proto_goTypes,
		DependencyIndexes: file_productServices_proto_depIdxs,
	}.Build()
	File_productServices_proto = out.File
	file_productServices_proto_goTypes = nil
	file_productServices_proto_depIdxs = nil
}
