package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	gen "github.com/ferza17/ecommerce-microservices-v2/api-gateway/model/rpc/gen/payment/v1"
)

// FindPaymentProviders is the resolver for the findPaymentProviders field.
func (r *queryResolver) FindPaymentProviders(ctx context.Context, input *gen.FindPaymentProvidersRequest) (*gen.FindPaymentProvidersResponse, error) {
	panic(fmt.Errorf("not implemented: FindPaymentProviders - findPaymentProviders"))
}
