package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"time"

	"github.com/ferza17/ecommerce-microservices-v2/api-gateway/model/graph/gen"
	"github.com/ferza17/ecommerce-microservices-v2/api-gateway/model/rpc/pb"
	"github.com/ferza17/ecommerce-microservices-v2/api-gateway/util"
)

// Products is the resolver for the products field.
func (r *findProductsWithPaginationResponseResolver) Products(ctx context.Context, obj *pb.FindProductsWithPaginationResponse) ([]*pb.Product, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *productResolver) CreatedAt(ctx context.Context, obj *pb.Product) (*time.Time, error) {
	return util.ConvertProtoTimestampToTime(obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *productResolver) UpdatedAt(ctx context.Context, obj *pb.Product) (*time.Time, error) {
	return util.ConvertProtoTimestampToTime(obj.UpdatedAt), nil
}

// DiscardedAt is the resolver for the discardedAt field.
func (r *productResolver) DiscardedAt(ctx context.Context, obj *pb.Product) (*time.Time, error) {
	return util.ConvertProtoTimestampToTime(obj.DiscardedAt), nil
}

// FindProductsWithPaginationResponse returns gen.FindProductsWithPaginationResponseResolver implementation.
func (r *Resolver) FindProductsWithPaginationResponse() gen.FindProductsWithPaginationResponseResolver {
	return &findProductsWithPaginationResponseResolver{r}
}

// Product returns gen.ProductResolver implementation.
func (r *Resolver) Product() gen.ProductResolver { return &productResolver{r} }

type findProductsWithPaginationResponseResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
