// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mongodb

import (
	"github.com/ferza17/ecommerce-microservices-v2/notification-service/pkg/logger"
)

// Injectors from wire.go:

func ProvideMongoDBInfrastructure() IMongoDBInfrastructure {
	iZapLogger := logger.NewZapLogger()
	iMongoDBInfrastructure := NewMongoDBInfrastructure(iZapLogger)
	return iMongoDBInfrastructure
}
